name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag public-ecr-aws:latest
    - name: Execute the scan
      run: docker run --rm public-ecr-aws:latest -max-crawl-depth 16 -threads 2000 -tag-threads 200 
    - name: Delete the Docker image
      run: docker rmi public-ecr-aws:latest
